### ISSUE TITLE
Example not working on Mac M2 Max Sonoma 14.4.1

### ISSUE THREAD

**Issue by gmlewis** [progrium/httpfs#2]
I tried the Flask example locally, and get:

```
$ httpfs -mount ~/demo ./examples/flask-basic/app.py
2024/04/19 09:03:27 unable to stat httpfs: Head "http://localhost:59353/": dial tcp 127.0.0.1:59353: connect: connection refused
```

I don't know much about Flask.  It might be nice to bundle a Go example as well.

I'm running on a Mac M2 Max with Sonoma 14.4.1.

**Comment by gmlewis** [comment]
It works great on Linux Mint 21.3 Cinnamon, by the way.
:tada:

**Comment by progrium** [comment]
I just pushed some changes that should fix this. I had it waiting 1 second for subprocess to start serving, but of course it could take longer. Now it polls until its up or gives up after 5 seconds.

I also added a Go example. Please let me know if this fixes.

**Comment by gmlewis** [comment]
I get the same thing with the Pyhon example... next, I'll try Go...

```
glenn@glenn-MacM2Pro ~/src/github.com/progrium/httpfs (main) $ git pull
Already up to date.
glenn@glenn-MacM2Pro ~/src/github.com/progrium/httpfs (main) $ httpfs -mount ~/demo ./examples/flask-basic/app.py
2024/04/19 13:17:57 unable to stat httpfs: Head "http://localhost:65276/": dial tcp 127.0.0.1:65276: connect: connection refused
```

**Comment by gmlewis** [comment]
Your Go example works!!!  🎉 

```
glenn@glenn-MacM2Pro ~/src/github.com/progrium/httpfs (main) $ httpfs -mount ~/demo ./examples/go-basic/go-basic
listening on :49502
```

```
glenn@glenn-MacM2Pro ~/ $ tree ~/demo
/Users/glenn/demo
└── hello

1 directory, 1 file
glenn@glenn-MacM2Pro ~/ $ cat ~/demo/hello
Hello world!
```

**Comment by gmlewis** [comment]
(Of course, I had to reboot the Mac after I add the executable to the security panel... ah, Macs.)

AH!  And _NOW_ the Flask version works too after the reboot!

So with the Go version, it forces you to update your system settings, whereas with the Flask version, it silently fails.
Feel free to close the ticket.
